# Generated by Django 4.2 on 2024-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='published_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
